[Application]
ActiveView = 'Services'
FontSize = 1800
Theme = 'Light'

[DevicesTable]
ColumnOrder = '0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17'
ColumnWidths = '250,303,80,80,80,100,300,300,100,100,80,80,80,80,80,80,80,80'
SortAscending = true
SortColumn = -1

[Logging]
LogLevel = 'debug'

[ModulesTable]
ColumnOrder = '0,1,2,3,4'
ColumnWidths = '150,80,250,883,100'
SortAscending = true
SortColumn = -1

[ProcessesTable]
ColumnOrder = '0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16'
ColumnWidths = '285,70,208,93,72,182,93,317,364,100,100,100,100,100,100,100,100'
SortAscending = true
SortColumn = -1

[ServicesTable]
ColumnOrder = '0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17'
ColumnWidths = '250,367,80,80,80,277,474,300,100,100,80,80,80,80,80,80,80,80'
SortAscending = true
SortColumn = -1

[UninstallerTable]
ColumnOrder = '0,1,2,3,4,5,6,7,8,9'
ColumnWidths = '250,100,150,300,300,100,100,200,150,150'
SortAscending = true
SortColumn = -1

[Window]
Height = 1417
Maximized = false
PositionX = 878
PositionY = 162
Width = 1838

[WindowsTable]
ColumnOrder = '0,1,2,3,4,5,6,7,8,9,10'
ColumnWidths = '100,250,150,100,120,100,100,80,80,80,150'
SortAscending = true
SortColumn = -1