[Application]
ActiveView = 'Devices'
FontSize = 2000
Theme = 'Dark'

[DevicesTable]
ColumnOrder = '0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17'
ColumnWidths = '285,786,81,93,73,182,93,317,93,93,93,93,93,93,93,93,93,93'
SortAscending = true
SortColumn = -1

[Logging]
LogLevel = 'debug'

[ServicesTable]
ColumnOrder = '0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17'
ColumnWidths = '285,786,81,93,73,182,93,317,93,93,93,93,93,93,93,93,93,93'
SortAscending = true
SortColumn = -1

[Window]
Height = 1129
Maximized = false
PositionX = 900
PositionY = 428
Width = 1690