[Application]
ActiveView = 'Windows'
FontSize = 1800
Theme = 'Dark'

[DevicesTable]
ColumnOrder = '0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17'
ColumnWidths = '285,786,81,93,73,182,93,317,93,93,93,93,93,93,93,93,93,93'
SortAscending = true
SortColumn = -1

[Logging]
LogLevel = 'debug'

[ModulesTable]
ColumnOrder = '0,1,2,3,4'
ColumnWidths = '150,80,250,500,100'
SortAscending = true
SortColumn = -1

[ProcessesTable]
ColumnOrder = '0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16'
ColumnWidths = '285,70,81,93,73,182,93,317,364,100,100,100,100,100,100,100,100'
SortAscending = true
SortColumn = -1

[ServicesTable]
ColumnOrder = '0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17'
ColumnWidths = '285,786,81,93,73,182,93,317,93,93,93,93,93,93,93,93,93,93'
SortAscending = true
SortColumn = -1

[Window]
Height = 1130
Maximized = false
PositionX = 1128
PositionY = 383
Width = 1690

[WindowsTable]
ColumnOrder = '0,1,2,3,4,5,6,7,8,9,10'
ColumnWidths = '250,180,120,100,80,200,400,300,150,120,80'
SortAscending = true
SortColumn = -1